version: "3"
services:
  jenkins:
    image: jenkins/jenkins:2.332-alpine
    ports:
      - "7001:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app

networks:
  app:
    external: true

