---
- name: Install the repository RPM
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: Instalar Docker
  apt:
    name: docker-ce
    state: latest

- name: Parar service Docker
  systemd:
    name: docker
    state: stopped

- name: Arrancar service Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Configurar docker_exporter
  template:
    src: "docker_exporter.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: 0644
