version: '3.1'
services:
  db:
    container_name: servidor_mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: asdasd
    restart: always
    networks:
      - test
    hostname: servidor_mariadb

networks:
  test:
    external: true
