version: '3.1'
services:
  app:
    container_name: servidor_web
    image: httpd:2.4
    restart: always
    ports:
      - 8080:80
    networks:
      - test
    hostname: servidor_web

networks:
  test:
    external: true
