version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - app

networks:
  app:
    external: true













