version: '3.7'
services:
  grafana:
    image: grafana/grafana:8.3.4
    ports:
      - 7006:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    networks:
      - app

networks:
  app:
    external: true
