version: '3.7'
services:
  alertmanager:
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    restart: always
    networks:
      - app

networks:
  app:
    external: true
