version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - 7008:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - app

networks:
  app:
    external: true
