---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install a list of packages
  apt:
    name: "{{ install_program }}"
    state: latest

- name: Start chrony service
  systemd:
    name : chrony
    state: started
    enabled: yes

- name: Zoneinfo dates
  shell: rm -f /etc/localtime; ln -s /usr/share/zoneinfo/UTC /etc/localtime
  args:
    executable: /bin/bash
