version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2   
    volumes:
      - logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - app

networks:
  app:
    external: true
